name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: BC-Li/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 71afd5e765f5238a565c9aa2b4d40ca9
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
